name: Telegram Notification on PR Creation

on:
  pull_request:
    types:
      - opened

jobs:
  telegram-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install python-telegram-bot requests

      - name: Send Telegram Message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: "Devops"  # Замініть на ваше користувачеське ім'я каналу
        run: |
          MESSAGE="New PR created: ${{ github.event.pull_request.html_url }}"
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID&text=$MESSAGE"